# apiVersion: v1
# kind: Secret
# metadata:
#   name: ecommerce-backend-database-connection
#   namespace: ecommerce
# type: Opaque
# stringData:
#   MARIADB_USERNAME: "ecommerceapp"
#   MARIADB_PASSWORD: "StrongPa55WorD"
#   MARIADB_DB: "full-stack-ecommerce"
#   MARIADB_HOST: "192.168.170.119"
#   MARIADB_PORT: "3306"
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-backend-database-connection
  namespace: ecommerce
type: Opaque
data:
  MARIADB_DB: ZnVsbC1zdGFjay1lY29tbWVyY2U=
  MARIADB_HOST: MTkyLjE2OC4xNzAuMTE5
  MARIADB_PASSWORD: U3Ryb25nUGE1NVdvckQ=
  MARIADB_PORT: MzMwNg==
  MARIADB_USERNAME: ZWNvbW1lcmNlYXBw