apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce

---

apiVersion: v1
kind: Service
metadata:
  name: ecommerce-backend-service
  namespace: ecommerce
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: ecommerce-backend
  type: ClusterIP