apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-pv
spec:
  capacity:
    storage: 10Gi
  accessModes: 
    - ReadWriteOnce
  nfs:
    path: /data/monitoring
    server: 192.168.170.119
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage